### ISSUE TITLE
Feature request - program devices without reset pin

### ISSUE THREAD

**Issue by angelnu** [voltlog/VoltLink#1]
First thanks a lot for the wonderful programmer - I ordered a couple and they have become my default programmer.

I would like to ask for an improvement when flashing devices that do not have a reset pin. Currently I deal with them by connecting the gpio0 pin to GND (I soldered a Pin to the VoltLink to make it easier) and then connect the USB. While this works it is not ideal as afterwards I have to disconnect the GPIO0 from GND and then re-connect the power to get a reset.

Would it be possible to have the 3.3 voltage output to follow the EN pin and so force the esp32 to reset?

**Comment by voltlog** [comment]
Hey! Happy to hear you like the Voltlink!

**Having the 3.3V rail follow any other signal would be a bad idea as that would potentially put a variety of devices into unknown states.  Most devices rely on that 3V3 rail being present while EN/IO0 are toggled.** 

As a simple workaround I would suggest installing a momentary NC switch on your 3V3 line between VoltLink and target so you can toggle it manually.
