### ISSUE TITLE
Invalid header error on Sonoff Zigbee bridge

### ISSUE THREAD

**Issue by MagicienFr** [voltlog/VoltLink#2]
Also the device is working very fine on Sonoff basic, I canot tasmotize the zbbridge with the device. The invalid header error is raised everytime. 
Also, the "self reseting" feature of tasmotizer windows 10 application doesn't seem to work: I use manual ground on IO0 to set the device in flash mode.

Does anybody have an advice?

Patrick

**Comment by voltlog** [comment]
This issue has nothing to do with the VoltLink.
I suggest using the tasmota web installer, that works fine for me.

**Comment by MagicienFr** [comment]
Hi, the tasmota web installer is providing the following error: The ESP board is not suported. 
Which sonoff zbbridge should I buy for make it work with your device?
thanks

**Comment by voltlog** [comment]
@MagicienFr The Sonoff zbbridge is not a good idea to start with, I have used in the past and it has poor performance. You should use a zigbee dongle plugged directly into HomeAssistant. The SONOFF ZBDongle-P should be a good start.
