### ISSUE TITLE
setup for Mac M1 - No compatible devices found.

### ISSUE THREAD

**Issue by roger-richards** [voltlog/VoltLink#3]
Bought a VoltLink and trying to use it with my Mac M1 Pro.  I downloaded the Silicon Labs "CP210x USB to UART Bridge VCP Drivers" for mac and installed, had to unblock the driver in System Preferences Security & Privacy pane.  If I run the following command in term: system_profiler SPUSBDataType
```
    USB 3.1 Bus:
      Host Controller Driver: AppleT6000USBXHCI

    USB 3.1 Bus:
      Host Controller Driver: AppleT6000USBXHCI

    USB 3.1 Bus:
      Host Controller Driver: AppleT6000USBXHCI
        VoltLink CP2102N USB to UART Bridge:
          Product ID: 0xea60
          Vendor ID: 0x10c4  (Silicon Laboratories, Inc.)
          Version: 1.00
          Serial Number: 8cd45e9f6754ed118fe443f71c62bc44
          Speed: Up to 12 Mb/s
          Manufacturer: Silicon Labs
          Location ID: 0x00100000 / 1
          Current Available (mA): 500
          Current Required (mA): 500
          Extra Operating Current (mA): 0
```
So the VoltLink shows connected to my Mac.  
When I try to use the Tasmota web installer or ESP-Flasher-macOSarm.app both of them say **no compatible devices found.**  I've confirmed that USB Serial connections are not blocked in Chrome. Also tried Edge.  Searched for a solution with no luck.  Do you have any recommendations? 

Did a bit more searching and someone reported a conflict after installing the Silicon Labs driver (since recent MacOS has a driver included.)  I uninstalled the Silicon Labs driver and still have my problem.  VoltLink shows up when connected but no app can detect the port.

**Comment by roger-richards** [comment]
Having installed and uninstalled the Silicon Labs driver twice, I decided to borrow a friend's MacBook M1 Air and web tasmotizer programmer worked immediately (no additional driver installed.) There is something about my MacBook M1 Pro that is preventing the various tasmotizer programmers from "seeing" the device (even though MacOS shows it is present.) Real mystery, but I have my tasmota device programmed and can finish my project.

**Comment by roger-richards** [comment]
If I find out what is blocking the programmer on my MacBook, I'll update this Issue. Closing for now

**Comment by voltlog** [comment]
@roger-richards Thanks! I'm looking into this as well by asking some friends with M processors to run some tests. I don't have any experience with MacOS and I'm generally noob level with Linux so I can't provide any help with debugging your particular issue. I'm just gonna try to confirm it's working on other setups.
